version: '3.8'
services:
  php:
    image: php:8.2.10-fpm
    volumes:
      - .:/var/www/html
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"
    networks:
      - my_network
  composer:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/setup-composer.sh:/var/www/setup-composer.sh
    command: /bin/bash /var/www/setup-composer.sh
    networks:
      - my_network

networks:
  my_network: